# Site settings
title: modulartex
header-img: img/home-bg.jpg
email: noah.harvey247@gmail.com
description: "Website for modulartex"
baseurl: ""
url: ""
twitter_username:
github_username:  theNerd247
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
